### ISSUE TITLE
用antd3.x和react16.x以上的版本使用不正常，能否更新到最新的依赖包。

### ISSUE THREAD

**Issue by liuyaoao** [leejaen/react-lz-editor#183]
源代码好像还有很多bug。我想改源码重新编译报错。

**Comment by alex-my** [comment]
看了DEMO和antd挺配的，不过antd(3.10.2)和react(16.5.2)运行报错

```text
ERROR 24959 [-/127.0.0.1/-/200ms GET /article/write] nodejs.ReferenceError: self is not defined
    at /Users/alex/MyWork/test/node_modules/whatwg-fetch/dist/fetch.umd.js:8:40
    at support.searchParams (/Users/alex/MyWork/test/node_modules/whatwg-fetch/dist/fetch.umd.js:2:66)
    at Object.<anonymous> (/Users/alex/MyWork/test/node_modules/whatwg-fetch/dist/fetch.umd.js:5:2)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/alex/MyWork/test/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/alex/MyWork/test/node_modules/react-lz-editor/global/supports/methods/Request.js:15:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/alex/MyWork/test/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/alex/MyWork/test/node_modules/react-lz-editor/global/supports/publicDatas.js:6:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
```

* 挺佩服作者的，项目需要就撸了一个(其实我也好想撸一个)。
* 后面回来再看看，目前作者时间不多，issue比较多。
