### ISSUE TITLE
引用报错

### ISSUE THREAD

**Issue by simlegate** [leejaen/react-lz-editor#34]
import LzEditor from 'react-lz-editor';

```
/Users/devinzhang/work/bzh-web/node_modules/antd/lib/style/index.css:9
html {
     ^
SyntaxError: Unexpected token {
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/devinzhang/work/bzh-web/node_modules/antd/lib/affix/style/css.js:3:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

**Comment by leejaen** [comment]
能不能描述的更清楚一下？

**Comment by simlegate** [comment]
@LeeHarlan  import之后就编译出错了。

**Comment by leejaen** [comment]
antd的版本多少？或重新安装一下包试试？上面的信息我不能定位到原因……

**Comment by LeeHarlan** [comment]
> antd的版本多少？或重新安装一下包试试？上面的信息我不能定位到原因……

+1

**Comment by simlegate** [comment]
antd的版本是^2.10.2.
react-dom的版本^15.5.4.
我是用这个模版来创建项目的： https://github.com/ant-design/react-starter-kit

**Comment by simlegate** [comment]
@leejaen Any update for this ?

**Comment by leejaen** [comment]
@simlegate The new version (0.10.16) has removed 'affix' toolbar, Pls reinstall it and check it if its worked.

**Comment by simlegate** [comment]
Thank your effect.
Unfortunately, It doesn't work yet.
