### ISSUE TITLE
点击上传图片、上传视频的那些图标都报错

### ISSUE THREAD

**Issue by vimplus** [leejaen/react-lz-editor#58]
在0.10.20这个版本点击上传图片、上传视频的那些图标都报错，报错如下：

```
Uncaught Error: must set key for <rc-animate> children
    at eval (webpack-internal:///./node_modules/rc-animate/es/Animate.js:220:19)
    at Array.map (native)
    at Animate.render (webpack-internal:///./node_modules/rc-animate/es/Animate.js:215:34)
    at p._renderValidatedComponentWithoutOwnerOrContext (https://cdn.bootcss.com/react/15.4.2/react-dom.min.js:13:10750)
    at p._renderValidatedComponent (https://cdn.bootcss.com/react/15.4.2/react-dom.min.js:13:10877)
    at performInitialMount (https://cdn.bootcss.com/react/15.4.2/react-dom.min.js:13:6696)
    at p.mountComponent (https://cdn.bootcss.com/react/15.4.2/react-dom.min.js:13:5742)
    at Object.mountComponent (https://cdn.bootcss.com/react/15.4.2/react-dom.min.js:14:18733)
    at performInitialMount (https://cdn.bootcss.com/react/15.4.2/react-dom.min.js:13:6856)
    at p.mountComponent (https://cdn.bootcss.com/react/15.4.2/react-dom.min.js:13:5742)
```

**Comment by leejaen** [comment]
上传后文件读取还有问题，我正在完善，这个错误请看这里： https://github.com/ant-design/ant-design/issues/2063

**Comment by vimplus** [comment]
老铁，加油，我等着上生产，下周还没解决估计我要另寻editor组件了>_<

**Comment by vimplus** [comment]
这个错误是因为你的demo配置里fileList: [""]引起的，写成fileList: []就没事

**Comment by leejaen** [comment]
最新版本0.10.21，包含示例，上传已验证通过自定义到又拍云。
